---
- name: mount global docker volume
  ansible.builtin.yum:
    name:
      - nfs-utils
      - nfs4-acl-tools
    state: present

- name: check mountpoint exist
  ansible.builtin.file:
    path: "{{ mountpoint }}"
    state: directory
    mode: "{{ permission }}"
    owner: root
    group: root

- name: mount network share
  ansible.posix.mount:
    src: "{{ mynfs }}"
    path: "{{ mountpoint }}"
    fstype: nfs
    opts: "{{ myopts }}"
    state: mounted
