---

- name: Check for Docker Repo
  stat:
    path: /etc/yum.repos.d/docker-ce.repo
  register: has_docker_repo

- name: Set up docker repository only if repository doesn't exist
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
    mode: '0644'
  when: not has_docker_repo.stat.exists

- name: Install the latest version of Docker Engine and containerd
  dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: latest   
  register:
    new_docker

- name: Enable service docker
  ansible.builtin.service:
    name: docker
    enabled: true
    state: started
      
- name: Add user to the docker group
  user:
    name: "{{ admin_user }}"
    groups: docker
    append: yes

- name: Reboot if Docker installed
  ansible.builtin.reboot:
  when: new_docker.changed
